# Generated by Django 5.1.15 on 2026-04-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_add_instagram_personal_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcredential',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('instagram_personal', 'Instagram (Personal)'), ('linkedin_personal', 'LinkedIn (Personal Profile)'), ('linkedin_company', 'LinkedIn (Company Page)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('threads', 'Threads'), ('bluesky', 'Bluesky'), ('google_business', 'Google Business Profile'), ('mastodon', 'Mastodon'), ('twitter', 'X (Twitter)')], max_length=30),
        ),
    ]
